const stateCodeAndNameMap = {
  Total: "total",
  Maharashtra: "mh",
  Kerala: "kl",
  "Uttar Pradesh": "up",
  Delhi: "dl",
  Rajasthan: "rj",
  Haryana: "hr",
  Telangana: "tg",
  Karnataka: "ka",
  Gujarat: "gj",
  Ladakh: "lh",
  Punjab: "pb",
  "Tamil Nadu": "tn",
  Chandigarh: "ch",
  "Andhra Pradesh": "ap",
  "Jammu and Kashmir": "jk",
  "Madhya Pradesh": "mp",
  "West Bengal": "wb",
  Uttarakhand: "ut",
  Odisha: "or",
  "Himachal Pradesh": "hp",
  Puducherry: "py",
  Chhattisgarh: "ct",
  "Andaman and Nicobar Islands": "an",
  Assam: "as",
  Bihar: "br",
  Meghalaya: "ml",
  Tripura: "tr",
  Goa: "ga",
  "Arunachal Pradesh": "ar",
  Jharkhand: "jh",
  Manipur: "mn",
  Mizoram: "mz",
  Nagaland: "nl",
  Sikkim: "sk",
  "Dadra and Nagar Haveli": "dn",
  "Daman and Diu": "dd",
  Lakshadweep: "ld",
  Unknown: "unknown"
};

module.exports = {
  stateCodeAndNameMap
}